# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
    push:

permissions:
    actions: read
    contents: read
    security-events: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true -c Release

            - name: Test
              run: dotnet test --no-build --verbosity normal -c Release

            - name: Install R# Global Tools
              run: dotnet tool install -g JetBrains.ReSharper.GlobalTools

            - name: Run R# Code Inspection
              run: jb inspectcode ./SleepingBear.Panda.sln -o=result.sarif
